### ISSUE TITLE
AttributeError: module 'tmap' has no attribute 'Minhash'

### ISSUE THREAD

**Issue by UnixJunkie** [reymond-group/map4#24]
```# ~/src/map4/map4/map4.py -i Ephrin.smi -o Ephrin.tsv
Traceback (most recent call last):
  File "/home/berenger/src/map4/map4/map4.py", line 182, in <module>
    main()
  File "/home/berenger/src/map4/map4/map4.py", line 137, in main
    calculator = MAP4Calculator(args.dimensions, args.radius, args.is_counted, args.is_folded)
  File "/home/berenger/src/map4/map4/map4.py", line 33, in __init__
    self.encoder = tm.Minhash(dimensions)
AttributeError: module 'tmap' has no attribute 'Minhash'
```

**Comment by UnixJunkie** [comment]
Which version of tmap are we supposed to use?

**Comment by UnixJunkie** [comment]
Can't this command:
```
pip install git+https://github.com/reymond-group/map4@v1.0
```
be made to pull all the required dependencies at an adequate version?

**Comment by UnixJunkie** [comment]
if MinHash is so important to map4, it should probably be included and not be provided by an external dependency

**Comment by LucaCappelletti94** [comment]
Did you end up finding how to get MinHash out of tmap?

**Comment by flogrammer** [comment]
Thanks so much @LucaCappelletti94 for creating a PR.

I was able to install it using
pip install git+https://git@github.com/reymond-group/map4.git@refs/pull/27/head
